name: Build Test

on:
  push:
    tags-ignore:
      - 'v*.*.*'
    branches:
      - '*'

jobs:
  build-webos:
    name: Build WebOS
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.2

      - name: Install Enact CLI and webOS CLI globally
        run: |
            npm install -g @enact/cli@6.1.1
            npm install -g @webos-tools/cli

      - name: Create workspace folder
        run: mkdir ~/webos-crunchy-test

      - name: Clone source repositories
        run: |
          cd ~/webos-crunchy-test
          git clone https://github.com/Lolo280374/crunchyroll-webos --recursive --single-branch --branch=stream --depth 3
          git clone https://github.com/ediaz23/crunchyroll-webos-service --single-branch --branch=master --depth 3
          git clone https://github.com/ediaz23/crunchyroll-webos-server --single-branch --branch=master --depth 3

      - name: Install dependencies for all projects
        run: |
          cd ~/webos-crunchy-test/crunchyroll-webos && npm install
          cd ~/webos-crunchy-test/crunchyroll-webos-service && npm install
          cd ~/webos-crunchy-test/crunchyroll-webos-server && npm install

      - name: Symlink service directory
        run: ln -s ../crunchyroll-webos-service ./service
        working-directory: ./webos-crunchy-test/crunchyroll-webos-stream


      - name: Build development package
        run: |
          cd ~/webos-crunchy-test/crunchyroll-webos
          npm run build-dev

      - name: Upload built app
        uses: actions/upload-artifact@v4
        with:
          name: webos-crunchy-app
          path: ~/webos-crunchy-test/crunchyroll-webos/bin/*
